exclude: ^README.md
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-yaml
        exclude: ^mkdocs
      - id: check-added-large-files
        args: ['--maxkb=2000']
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.1
    hooks:
      - id: markdownlint-cli2
    # exclude: ^README.md
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.5'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        files: (src/pbb/)
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
    - id: black
      language: python
      args:
        - "--line-length=88"
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
