name: Publish Docs without PDF

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      directory:
        description: 'Release it'
        default: 'gogogo'
        required: false


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.14"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 2.1.2
      - name: Install dependencies
        run: |
          poetry --version
          poetry install
      - uses: nikeee/setup-pandoc@v1
      - name: build and publish
        run: poetry run mkdocs gh-deploy --force
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
